name: smartedge
version: 0.1
summary: A new way to integrate cloud, IoT and other devices
description: A new way to integrate cloud, sensors, actuators, and all types of devices and services on a smart edge device.
confinement: strict
grade: stable

apps:
    smartedge:
        command: smartedge $1
        plugs: [network-bind, network]
parts:
     smartedge:
        plugin: go
        source: src/smartedge
